### ISSUE TITLE
Fails with `PSTFile::findBtreeItem Unable to find 97 is desc: true`

### ISSUE THREAD

**Issue by jasonpolites** [epfromer/pst-extractor#5]
Fails for me with all PST files I try:

```
Error: PSTFile::findBtreeItem Unable to find 97 is desc: true
    at PSTFile.findBtreeItem (/[REDACTED]/pst/node_modules/pst-extractor/dist/PSTFile/PSTFile.class.js:549:23)
    at PSTFile.getDescriptorIndexNode (/[REDACTED]/pst/node_modules/pst-extractor/dist/PSTFile/PSTFile.class.js:562:73)
    at PSTFile.processNameToIDMap (/[REDACTED]/pst/node_modules/pst-extractor/dist/PSTFile/PSTFile.class.js:140:46)
    at new PSTFile (/[REDACTED]/pst/node_modules/pst-extractor/dist/PSTFile/PSTFile.class.js:114:14)
```

**Comment by epfromer** [comment]
Please try with the PSTs in the __tests__/testdata folder and tell me if that works for you.

**Comment by matthiasg** [comment]
I have the same issue with a number of pst files not all though
